enzo-project/enzo-e

- src/Cello/io_OutputData.cpp
Bugfix in particle output when number of particles is zero. The associated groups in the HDF5 output file would still be created in this instance, but not closed properly. This caused a lock on the output file after IO was over unless the simulation completed with a clean exit. If not, the output data was corrupted.
One other solution is to not create the groups in the first place if the number of particles is zero, but this would lead to inconsistencies in data format if a simulation starts without particles but forms some later on. I prefer creating the (empty) groups if user requests particle output but there happen to be no particles.
> Particle IO Bugfix

- src/Cello/data_FieldFace.cpp
- src/Cello/data_FieldFace.hpp
- src/Cello/io_IoFieldData.cpp
Addresses the bug in saving face-centered fields to HDF5 files that caused the data to be clipped. This occurred because the IoFieldData::field_array method (which retrieved field data and its iteration limits for copying the data to the hdf5 file) determines the iteration limits by calling FieldData::size and it never checked the field's centering (which effectively assumes that all fields are face-centered).
The bugfix now has IoFieldData::field_array check field centering and adjusts the iteration limits accordingly.
> Face-Centered Field IO Bugfix

- .circleci/config.yml
- build.sh
- config/linux_gnu.py
This provides some initial testing with the CircleCI service. Currently, this will only compile the code, but we can add the testing bit later.
I also added the ability to set PAPI paths to the linux_gnu makefile and simplified a couple things.
> Enable CI testing with circleci

- SConstruct
- config/linux_gnu.py
- src/Enzo/_enzo.hpp
- src/Enzo/enzo_EnzoConfig.cpp
- src/Enzo/enzo_EnzoConfig.hpp
- src/Enzo/enzo_EnzoMethodGrackle.cpp
Made changes to allow for compilation without grackle installation. 
Also made a minor tweak to the SConstruct file and config/linux_gnu.py to address a problem with compiling the fortran files.
> Fixed bugs related to compiling enzo-e without grackle

- .gitignore
- doc/source/_static/theme_overrides.css
- doc/source/conf.py
I modified the .gitignore file to ignore directories and binaries created during the build process.
I also modified the document generation files to enable text wrap-around in documentation. Prior to this change, tables are stretched out such that text in a given cell sits on a single line. This isn't a problem for the current documentation, but it becomes problematic in the new documentation included in Pull Request #9.
To provide an example, here is how a table is currently rendered:
And here is how a table is rendered after the change:
> Tweak to .gitignore and adding wraparound to documentation

- input/method_grackle.in
- src/Enzo/enzo_EnzoMethodGrackle.cpp
- src/Enzo/enzo_EnzoMethodGrackle.hpp
The main issue was that `EnzoMethodGrackle`'s `timestep` instance method, declared in `src/Enzo/enzo_EnzoMethodGrackle.hpp` and implemented in `src/Enzo/enzo_EnzoMethodGrackle.cpp`, was not const-qualified. In contrast, the virtual method declared in the `Method` super-class (the one Cello uses to compute the timestep) is const-qualified. As a result, the old implementation had been providing an unused overload of the `timestep` method. When Cello was calling the `timestep` method of an instance of `EnzoMethodGrackle`, the default implementation provided for `Method::timestep` was used, which simply returned `std::numeric_limits<double>::max()`.
This bugfix can be tested by adding setting the Method::grackle::use_cooling_timestep parameter to true in `input/method_grackle.in`. Prior to …
> Fixed a bug that had prevented the use of the grackle cooling timestep.

- SConstruct
- src/Enzo/enzo_EnzoMethodGrackle.cpp
Fixing bug that cause simulation to hang using Grackle method in AMR runs. compute_done now properly called.
> Grackle bugfix

- config/_common_search_paths.py
- config/linux_gnu.py
- config/linux_intel.py
- config/stampede_gnu.py
- config/stampede_intel.py
I updated the configuration files (`stampede_gnu.py` and `stampede_intel.py`) for building Enzo-E on Stampede2 and I have confirmed that Enzo-E is successfully compiled using both compilers. Additionally, I factored out the duplicate code used to search for the ``charm_path`` and ``grackle_path``, from the ``linux_gnu.py`` and ``linux_intel.py`` configuration files into dedicated functions in ``_common_search_paths.py`` (these functions are now used in all four of these configuration files).
I just wanted to note that when building on stampede2, using either compiler, Scons raises an error (detailed in Issue #28 ). This error arises at the very end of the installation and doesn't seem to have any actual effect.
> Updated Stampede Build Files

- src/Cello/problem_Problem.cpp
- src/Cello/problem_Problem.hpp
- src/Enzo/enzo.cpp
- src/Enzo/enzo.hpp
- src/Enzo/enzo_EnzoComputeCoolingTime.cpp
- src/Enzo/enzo_EnzoComputePressure.cpp
- src/Enzo/enzo_EnzoComputeTemperature.cpp
- src/Enzo/enzo_EnzoConfig.cpp
- src/Enzo/enzo_EnzoConfig.hpp
- src/Enzo/enzo_EnzoInitialGrackleTest.cpp
- src/Enzo/enzo_EnzoMethodGrackle.cpp
- src/Enzo/enzo_EnzoMethodGrackle.hpp
This PR refactors calls to the external Grackle library to resolve SMP-mode issues.
**Problem Overview:**
The current procedure for setting up the `chemistry_data` struct on each PE (Processor Element) can be summarized by the following 2 steps:
1. `EnzoConfig` dynamically allocates a local `chemistry_data` struct on each PE (Processor Element). It then calls `set_default_chemistry_parameters`, which both assigns this struct the default parameters and sets the global variable `grackle_data` equal to the address of this struct. Finally, the parameter file values are assigned to the appropriate fields of the struct that is pointed to by `grackle_data`. Note that the `EnzoConfig` destructor will deallocate the locally allocated struct.
2. The constructor for `EnzoMethodGrackle` calls the …
> Threadsafe Grackle Changes

- .circleci/config.yml
This doesn't change any commands, just adds a name to each section of the build. The only thing this does is make it so the steps on circleci have easily parsable names instead of a word salad of all the commands being run.
> Add name to job commands.

- src/Cello/test_CelloArray.cpp
- test/ArrayComponent/SConscript
- test/SConscript
This PR reintroduces the CelloArray Unit Test to the testing framework. The unit test itself was originally created, added to the testing framework, and reviewed as PR #62. However, the test seems to have fallen through the cracks while merging with the test overhaul PR.
This PR simply remedies that situation. 
I also made a very minor tweak to the unit test itself to address complaints from the compiler about non-compliance with C++11. I literally just replaced `typename` in some nested templates with `class`.
> Reintroducing CelloArray Unit Test

- SConstruct
- config/msu_hpcc_gcc.py
- doc/source/tutorial/getting_started.rst
Assuming we want additional machine file also for smaller centers, this one uses only module provided by the center (i.e., apart from grackle no custom libraries need to be installed).
I also added a note on using `++local` as this came up now several times on Slack.
> Add machine file and update doc for node local runs

- doc/source/tutorial/getting_started.rst
In PR #96 I was informed that Enzo-E's build infrastructure did already have a way of specifying the Grackle installation folder (the ``GRACKLE_HOME`` environment variable) that I didn't know about. I have added this to the installation documentation, along with a bit of advice I received for debugging Charmrun timeouts.
> Installation doc tweaks

- input/Adapt/adapt.incl
- input/Balance/load-balance-4.in
- input/Schedule/schedule_time_0.01.incl
- src/Enzo/enzo_EnzoMethodPpml.cpp
- test/MeshGeneration/SConscript
CircleCI tests have been failing due to timing out on individual tests.  While testing needs some more serious updating to bring everything back online again (unit tests, cosmology, etc.), this is intended as a quick fix to shorten the time of longer tests so that CircleCI doesn't time out.  With the current tests being run, that's just "adapt-L5", which does simple hydro on a 2D AMR mesh, and "mesh-balanced", which is obsolete and redundant with adapt-L5 (it doesn't test load balancing as its current categorization would indicate; "balanced" here refers to maintaining the 2-1 mesh refinement jump limit).  When cosmology tests get re-added back in they will need to be updated to shorten their times as well.
> Shorten testing

- test/Restart/SConscript
- tools/ckpt_restart_test.py
There were a few lingering references to enzo-p in the restart tests.
> Updated references from 'enzo-p' to 'enzo-e'.

- .circleci/config.yml
- build.sh
- doc/source/tutorial/getting_started.rst
I got tired of stashing my changes to `build.sh` because I had `proc` a different value 😄 
By default, it will use all of the cores.  This can be overridden by setting either the proc variable in build.sh or the environment variable `CELLO_BUILD_NCORE`. I couldn't test whether this works on macOS
```
sysctl -n hw.ncpu
```
It'd be great if someone with macOS could test whether this command gives the number of cores.
> Auto-detect the number of cores in the build script

- input/vlct/passive_advect_sound_wave/passive_advection_test.incl
- src/Enzo/enzo_EnzoCenteredFieldRegistry.hpp
- src/Enzo/enzo_EnzoInitialCloud.cpp
Last week we pulled in a PR (I think it was #49) that changed instances of "colour" to "color". This updates the remaining instances in the VL+CT-related machinery.
> Convert remaining "colour" instances to "color"  

- .circleci/config.yml
- src/Enzo/enzo_EnzoConfig.cpp
PR #49 introduced a minor change that breaks builds without Grackle (again). 
I've fixed this locally (it's a really easy fix). But I'm taking this as an opportunity to try to setup a CircleCi test to verify that Enzo-E can be built without Grackle (Our other tests already take a while, so I'm not going to run any tests with this build; I'm just checking if the build succeeds). 
I'm intentionally going to make some tests fail while testing this, but this will be ready for review by tomorrow. (I'll change this from WIP once it's ready and I'll add an edit to this post confirming that it's ready).
EDIT: I'm done. This is now ready for review.
> Fixing another bug related to builds without Grackle

- src/Enzo/enzo_EnzoInitialFeedbackTest.cpp
Tiny PR to resolve #127 (which documents a compiler error that arises from not including `<fstream>` in `enzo_EnzoInitialFeedbackTest.cpp`)
> `<fstream>` hotfix

- src/Cello/error_Error.cpp
- src/Cello/error_Error.hpp
Apologies for the influx of small pull requests. But this one should be extremely easy to review.
For the following snippet of code:
```
int foo(char arg){
if (arg == 'a'){
return 0;
} else if (arg == 'b'){
return 1;
}
ERROR("foo", "arg must be 'a' or 'b'");
}
```
The compiler would have previously issued a warning (depending on the compiler flags) saying complaining that we are missing a return statement at end of a non-void function. The same thing would happen if we replaced the if-statement with an exhaustive switch statement.
However, now that we have introduced this attribute, the compiler now understands that we will never reach the end of the `foo` function when we raise an error and it will no longer issue a warning.
More details about the `noreturn` attribute can be found here: …
> Annotated ``cello::error`` with the ``[[noreturn]]`` attribute

- src/Cello/parameters_Config.cpp
Lines 695-729 have been added to Config::read_mesh_ in src/Cello/parameters_Config.cpp file as requested in Issue 109.
> Enforce Ghost Depth Constraints on Block Size #109

- build.sh
- input/Checkpoint/checkpoint_vlct.in
- src/Enzo/enzo_EnzoConfig.hpp
- test/Restart/SConscript
It's come to my attention that the checkpoint-restart test for the VL+CT test is failing. I've confirmed that it's breaking for a very simple reason (I forgot to add the `Method:mhd_vlct:mhd_choice` parameter to the input file in PR #74).
But before I upload the commit solving this problem, I'm first going to make sure I've resolved a minor bug in `build.sh` that had let the script exit with an exit-code indicating success, even when some tests crashed. I believe, this prevented the bug from being reported by the Continuous Integration (in other words, I want to confirm that the Continuous Integration reports a failure once I've fixed the bug in `build.sh`, but not the VL+CT checkpoint bug).
**EDIT:** This is now ready for review. I also had to update the PUP routine for Grackle's …
> Quick Bugfix in RestartTest

- input/vlct/run_HD_linear_wave_test.py
- input/vlct/run_MHD_linear_wave_test.py
- input/vlct/run_MHD_shock_tube_test.py
- input/vlct/run_dual_energy_cloud_test.py
- input/vlct/run_dual_energy_shock_tube_test.py
- input/vlct/run_passive_advect_sound_test.py
- input/vlct/testing_utils.py
- test/run_vlct_test.sh
I've made 2 main changes to the python scripts used to run the VL+CT tests.
1. I made it possible to run those scripts from any directory. This should help a lot with executing these tests using `ctest` (in https://github.com/jobordner/enzo-e/pull/4 ). Longer term, we might want to refactor some of these tests.
2. I tweaked `run_dual_energy_shock_tube_test.py` to let you run the test in parallel with `charmrun` when it's not in your `PATH` (this was an oversight). This is done by looking at the `CHARM_HOME` directory.
> Update vlct test scripts

- src/Cello/cello.cpp
The function in question did not return any values (when it should have been returning the id of the newly created field). 
This caused the function to cause a segmentation fault whenever it was executed while using the default settings for `linux_gnu` (which involve heavy optimizations), with at least some version of gcc (I encountered the issue with version 9.3.0).
The only automated test that executed this function is currently the Checkpoint-Restart test for `EnzoMethodGrackle`. But to be clear, ANY simulation involving Grackle would be affected by this bug (there just aren't any other automated tests involving Grackle).
> `EnzoMethodGrackle` Hotfix: Fixed bug in `cello::define_field_in_group`

- src/Enzo/FofLib.cpp
As the title implies, this avoids several unnecessary casts from ``const char*`` to ``char*`` (which previously raised compiler warnings)
> Address compiler warning - stop implicit cast from ``const char*`` to ``char*``

- input/Checkpoint/checkpoint_grackle.in
- input/PPML/ppml.incl
- src/Cello/parameters_Config.cpp
- src/Cello/parameters_Config.hpp
This bug arose because of an annoying property of `std::map`:
- In this scenario, `field_index` is an instance of `std::map<std::string,int>` that maps field names to field indices.
- While adding fields to groups, based on an input configuration file, the old code checked for the index associated with a field name, `field`, using `field_index[field]`.
- Unfortunately, if `field` is not already contained by `field_index`, a new key-value pair is inserted into `field_index` (This is required to support the syntax like `field_index["density"] = 3;`).
- As a result, when users tried to add previously undeclared fields to a group, a different field was added to the group instead.
An alternative fix would be to replace `field_index[field]` with `field_index.at(field)`. In cases where …
> Bugfix: add nonexistent field to group

- input/IsolatedGalaxy/WLM_small.in
- input/IsolatedGalaxy/method_isolatedgalaxy-particles.in
- input/IsolatedGalaxy/method_isolatedgalaxy.in
- input/bb_unigrid_SF_FB.in
- input/method_feedback.in
- src/Enzo/enzo_EnzoConfig.cpp
- src/Enzo/enzo_EnzoConfig.hpp
- src/Enzo/enzo_EnzoMethodBackgroundAcceleration.cpp
- src/Enzo/enzo_EnzoProblem.cpp
Previously, the `star_maker` and `background_acceleration` methods had a `type` parameter, which was used to set different behaviours for these methods. However, this commit (which was part of PR #97): https://github.com/enzo-project/enzo-e/commit/1cfa4721f8fc04e6a28de6f4d0065691eee45415, introduced a `Method:type` parameter, which led to a conflict.
To get around this, I have replaced `Method:star_maker:type` with `Method:star_maker:flavor` and `Method:background_acceleration:type` with `Method:background_acceleration:flavor`.
> Rename "type" parameter of star_maker and background_acceleration methods to "flavor" (bugfix)

- CMakeLists.txt
- test/CMakeLists.txt
- tools/run_cpp_test.py
In the process of porting the C++ unit tests and the tests that compare the final simulation time or final cycle to the actual simulation time/cycle at the end of an Enzo-E simulations, there was a minor oversight  that reduced the functionality of these tests. 
The new system implicitly assumes that the exit code of these C++ tests always indicated whether the test passed or not. However, that is not presently the case (as long as the program gracefully exits, it reports an exit code of 0). As a consequence, a test could fail (e.g. the final simulation time could be different from the expected final time), but CTest would still report the test as passing. As a concrete example, one can do the following:
- modify line 79 of `input/PPM/ppm.incl` so that you replace `time_final  = …
> Address minor oversight in the ported tests

- tools/run_cpp_test.py
Teeny-tiny fix to allow arguments that begin with a dash (required for some charm++ builds).
> Very small fix to test_cpp_test.py

- input/merge_sinks/merge_sinks_test.in
Fixed bug in `"merge_sinks"` tests: input parameter file now specifies that sink particles are in the `"is_gravitating"` group, which ensures that the `"pm_update"` method updates the particle positions, which means that the particles move towards each other and merge.
> Bugfix for "merge_sinks" tests 

- .gitignore
- input/Hydro/tracer.incl
- input/IsolatedGalaxy/WLM_small.in
- input/IsolatedGalaxy/method_isolatedgalaxy-particles.in
- input/IsolatedGalaxy/method_isolatedgalaxy.in
- input/Particle/test_particle.incl
- input/Sedov/config/config-trace-on.incl
- input/bb_unigrid_SF_FB.in
- input/method_feedback.in
As discussed in #197, a precision mismatch can happen between the particle attributes and fields. A short-term solution is to set the attribute precision to "default" instead of single or double in the offending parameter files, which this PR addresses.
> Changing single/double particle precision in parameter files to default

- input/test_cosmo.incl
Very small fix to test_cosmo.incl so that it runs -- initializing DM mass as "mass" (not "density"). These files didn't get updated after PR #89 merged
> Fixing particle mass in test_cosmo.incl

- doc/source/tutorial/getting_started.rst
Clarifying that you would use `-DPNG_ROOT` instead of `-DLIBPNG_ROOT`
> Clarify how to specify libpng installation path.

- src/Cello/cello.hpp
- src/Cello/problem_Units.hpp
- src/Enzo/_enzo.hpp
- src/Enzo/enzo_EnzoConfig.cpp
- src/Enzo/enzo_EnzoInitialBurkertBodenheimer.cpp
- src/Enzo/enzo_EnzoInitialCollapse.cpp
- src/Enzo/enzo_EnzoInitialFeedbackTest.cpp
- src/Enzo/enzo_EnzoInitialGrackleTest.cpp
- src/Enzo/enzo_EnzoInitialIsolatedGalaxy.cpp
- src/Enzo/enzo_EnzoMethodBackgroundAcceleration.cpp
- src/Enzo/enzo_EnzoMethodDistributedFeedback.cpp
- src/Enzo/enzo_EnzoMethodFeedback.cpp
- src/Enzo/enzo_EnzoMethodFire2Feedback.cpp
- src/Enzo/enzo_EnzoMethodStarMaker.cpp
- src/Enzo/enzo_EnzoMethodStarMakerFIRE2.cpp
- src/Enzo/enzo_EnzoMethodStarMakerStochasticSF.cpp
- src/Enzo/enzo_EnzoPhysicsCosmology.hpp
- src/Enzo/enzo_EnzoUnits.hpp
- src/Enzo/enzo_constants.hpp
As we discussed this morning I moved the Physics constants from the Cello layer to the `Enzo` layer.
I went a little off script here and put the constants into a new namespace called `enzo_constants`. If people would prefer otherwise, I can easily put them into the existing `enzo` namespace
~EDIT:I didn't compile the code first. There's a few things I need to fix~ It compiles now
> Moved physics constants from Cello layer to Enzo layer

- input/IsolatedGalaxy/WLM_small.in
- input/IsolatedGalaxy/method_isolatedgalaxy-particles.in
- input/IsolatedGalaxy/method_isolatedgalaxy.in
- src/Enzo/enzo_EnzoConfig.cpp
- src/Enzo/enzo_EnzoConfig.hpp
- src/Enzo/enzo_EnzoInitialIsolatedGalaxy.cpp
- src/Enzo/enzo_EnzoMethodBackgroundAcceleration.cpp
In the original version of the initializer, the halo mass can be derived from the central DM density. This is triggered by giving a negative halo mass and a non-zero DM density. However, there was one calculation in the initializer that wasn't checking whether the halo mass was negative, resulting in a NaN after a sqrt. This PR fixes this issue.
> [BUGFIX] Isolated galaxy velocity calculation

- src/Enzo/enzo_EnzoSolverJacobi.cpp
Simple bugfix, which came down to removing a call to a function that no longer exists, which somehow came about when PR #126 was merged into `main`.
I presume it is safe to remove, since none of the other `Solver` classes call the function in their constructor methods, but perhaps @jobordner should confirm.
> [BUGFIX] Removed line of code which caused compilation to fail

- doc/source/tests/adapt-cmake.rst
- doc/source/tests/array-cmake.rst
- doc/source/tests/balance.rst
- doc/source/tests/boundary-cmake.rst
- doc/source/tests/checkpoint.rst
- doc/source/tests/error-cmake.rst
- doc/source/tests/fluxcorrect-cmake.rst
- doc/source/tests/grackle-cmake.rst
- doc/source/tests/gravity-cmake.rst
- doc/source/tests/heat-cmake.rst
- doc/source/tests/helloworld-cmake.rst
- doc/source/tests/hydro.rst
- doc/source/tests/index.rst
- doc/source/tests/initialmusic-cmake.rst
- doc/source/tests/isolatedgalaxy.rst
- doc/source/tests/memory-cmake.rst
- doc/source/tests/mergesinks-cmake.rst
- doc/source/tests/monitor-cmake.rst
- doc/source/tests/others.rst
- doc/source/tests/output-cmake.rst
- doc/source/tests/parse.rst
- doc/source/tests/particle-cmake.rst
- doc/source/tests/ppm-cmake.rst
- doc/source/tests/testing_environment.rst
- doc/source/tests/vlct-cmake.rst
- doc/source/tests/vlct.rst
In the testing environment page, we updated the list of tests that are currently included in the ctest and created a new subsection for all the available tests in the input folder (#177) . The pages are created but explanations for the tests are left as "Under construction".
We also fixed the issue in #222.  
**Note: We didn't check how does it look in the browser.**
Vanesa and @buketbenek
> Test documentation updated #177 and fixing #222

- doc/source/conf.py
Last week @jobordner pointed out that calls to doxygen were significantly slowing down local rebuilds of the website (since doxygen got called every time we rebuilt the website docs).
To improve the situation, I have modified the configuration script to check the most recent modification timestamps of all files and directories in the `doc/dox-xml` directory (if it exists) and the `src` directory against cached values (if they exist). 
- doxygen is only invoked if the values disagree, `doc/dox-xml` doesn't exist, or the cached values can't be found.
- The cached values are saved in a json file at `doc/cached_mtimes.json`
- A simple test, where I rebuild the documentation immediately without any changes indicates that I have cut the build time from 47 seconds down to 0.6 seconds.
As an …
> Faster local doc rebuilds (avoid unnecessary calls to doxygen)

- doc/source/tutorial/getting_started.rst
This is required for yt to be able to read particle masses correctly following PR #89
> Added instructions for how to install yt from source to "Getting started"

- CMakeLists.txt
- src/Cello/_io.hpp
- src/Cello/io_Output.hpp
- src/Cello/io_OutputData.cpp
- src/Cello/monitor_Monitor.cpp
- src/Cello/problem_MethodOutput.cpp
We talked about doing this last week. It should help with handling new-features in the yt-frontend as we go forward. The version number comes from the `CMakeLists.txt` file. The way I have implemented this is not necessarily the cleanest way to do it, but I tried to make it easy to also add to the new checkpoint outputs when that gets merged in. We may eventually want to differentiate between Cello and Enzo-E versions, but this seemed like a good start.
I have confirmed that this works properly when we use the old output approach (specifying outputs in the output section of the parameter file) and with the new output approach (specifying outputs in the Method section of the parameter file). I have not added a test, but I can probably do so if you think that would be helpful.
You can …
> Write the version number as a file-level attribute of output hdf5 files

- src/Enzo/enzo_EnzoInitialCosmology.cpp
- src/Enzo/enzo_EnzoMethodGrackle.cpp
- src/Enzo/enzo_EnzoProblem.cpp
- src/Enzo/enzo_EnzoSimulation.cpp
This is a small PR that fixes a bug that I tried to address in PR #143, but the bug came back after PR #234 for some reason. I think I've found a more permanent fix. 
The issue is that for cosmology simulations, redshift, simulation time, and units aren't set until after all of the methods, initializers, etc. are initialized (see `EnzoSimulation::r_startup_begun`). `EnzoMethodGrackle` currently calls `initialize_grackle_chemistry_data()` in the constructor. `initialize_grackle_chemistry_data()` references `setup_grackle_units()`, which stores all of our code units into an object called `grackle_units` that gets passed into all of the Grackle-related functions throughout the course of the simulation. Since cosmology units haven't been properly initialized by the time …
> Bugfix: Cosmology units with Grackle

- input/Checkpoint/checkpoint_grackle.in
- input/test_cosmo-dd-multispecies.in
The "gamma" field first appeared in the input files during an earlier version of Enzo-E. However back in PR #1, it was removed (Grackle no longer uses it). If we wanted, it would be straightforward to output it as a derived quantity, but for the short-term, it's better not to include it (to avoid confusing new users).
While I was doing this, I fixed a couple of cases where the "temperature", "pressure", "cooling_time" fields were all listed as part of the "color" field. This also crept in as part of an older version of a Grackle input file and could definitely cause problems (since these fields are not passively advected scalars).
> Removed all mentions of `"gamma"` field from input files.

- .circleci/config.yml
Use the latest gold standard tag for answer testing on circleci.
> Use gold standard for answer testing.

- src/Enzo/enzo_EnzoPhysicsCosmology.hpp
This PR is making the changes to `enzo_EnzoPhysicsCosmology.hpp` that @stefanarridge suggested to address issue #243. With these changes, the units printed out during cycle 0 of `test_cosmo-dd.in` are the following:
```
cosmology->density_units()  = 2.76e-24
cosmology->length_units()   = 1.32e+23
cosmology->time_units()     = 6.57e+14
cosmology->velocity_units() = 2.01e+08
```
These are the same values that were printed out for the same test pre PR #243, so I think the units are correct now.
> Fixing cosmology density and velocity units (see issue #243)

- doc/source/param/method_feedback.incl
- doc/source/param/method_star_maker.incl
- input/STARSS/SF_FB.incl
- input/STARSS/method_feedback_starss.in
- src/Enzo/enzo_EnzoConfig.cpp
- src/Enzo/enzo_EnzoConfig.hpp
- src/Enzo/enzo_EnzoMethodFeedbackSTARSS.cpp
- src/Enzo/enzo_EnzoMethodFeedbackSTARSS.hpp
- src/Enzo/enzo_EnzoMethodStarMaker.cpp
- src/Enzo/enzo_EnzoMethodStarMaker.hpp
- src/Enzo/enzo_EnzoMethodStarMakerSTARSS.cpp
This PR makes some very minor changes to the STARSS methods -- mostly just resetting the default parameters for `EnzoMethodFeedbackSTARSS` and updating the documentation. 
I also noticed that `EnzoMethodStarMaker::check_jeans_mass()` was written to return `true` if the cell mass is **less** than the Jeans mass, so I corrected it to be the other way around (`return true` if `Mcell > Mjeans`).
> STARSS small changes

- input/Gravity/jeans_wave/initial_jeans.incl
- src/Enzo/enzo_EnzoMethodPmDeposit.cpp
This PR was primarily written to implement a bugfix (relevant to PR #187), but I got a little carried away with some refactoring.
The first 2 commit lightly refactors `EnzoMethodPmDeposit::compute`. I have summarized these changes in the following spoiler tag.
<details> 
<summary> Refactoring changes </summary>
* the method is now broken up into some local helper functions, which should make the logic easier to understand. Previously the method was 430 lines long and it was a little difficult to determine which variables used for Particle-mass deposition affected the gas-mass deposition.
* removed some unnecessary heap-allocations from the gas deposition
* transitioned the heap allocations to make use of `std::vector` and `CelloArray` (so that we don't need to explicitly deallocate the …
> Light refactor of `EnzoMethodPmDeposit::compute` and gas-deposition drift-time bugfix

- doc/source/_static/roles.css
- doc/source/conf.py
- doc/source/param/method.incl
- doc/source/param/method_mhd_vlct.incl
- doc/source/param/method_star_maker.incl
This PR:
- fixes some RST markup issues in the parameters section, including ones that prevented `method_star_maker.incl` and `method_feedback.incl` from being included
- addresses a compatibility issue with newer Linux distributions related to including style sheets,
- orders method parameter subsections to be alphabetical,
- re-adds a long-gone style sheet for implementing `roles.incl` markup in parameter headers, and
- replaces my name with "Enzo Development Community" in copyright notices
See http://client64-71.sdsc.edu/~bordner/enzo-e.jobordner.fix-docs/doc/build/html/ for rendered version.
A more thorough documentation review will be forthcoming.
> Fix documentation markup issues

- CMakeLists.txt
This sets the version number recorded in the output hdf5 files.
We might want to make a test to make sure these this stays synchronized with the git tag (if it's not a gold standard test). But that's a problem for a different day
> Update the version number recordered in CMakeLists.txt 

- src/Enzo/enzo_EnzoMethodPmDeposit.cpp
PR #239 introduced a minor bug in which array used for storing the output of dep_grid_cic was not large enough. This caused dep_grid_cic to write values to invalid locations in memory. This bug manifested in weird ways when using compiling with intel compilers (under special conditions)
In addition to fixing that bug, some variable names were updated so that their significance is more obvious
> Fix bug from PR#239 in EnzoMethodPmDeposit

- .circleci/config.yml
Tests were failing because CircleCI wasn't fetching the tags. Now they pass again
> Force CircleCI to fetch tags for gold-standard

- cmake/FindCharm.cmake
Newer versions of charm++ (starting at least in version 7.0) appear to define the macro specifying SMP usage in a different header file than the one we checked.
Prior to this commit, CMake would always effectively assume that these newer versions of charm++ were built without SMP mode
> [Bugfix] CMake checks whether charm++ was compiled with SMP mode in multiple places.

- src/Enzo/enzo_SolveHydroEquations.cpp
- src/Enzo/enzo_fortran.hpp
- src/Enzo/ppm_de.F
- src/Enzo/xeuler_sweep.F
- src/Enzo/yeuler_sweep.F
- src/Enzo/zeuler_sweep.F
This is a small PR that adds the ability to set a density floor in EnzoMethodPpm, since the method doesn't currently check `enzo_fluid_floor_config.density()` anywhere.
I've also made the small change of passing density and pressure floors into `ppm_de` as parameters. In the main branch, these are currently hard-coded to be arbitrarily small numbers in `ppm_de` (for pressure_floor) and `<x/y/z>euler_sweep` (for density_floor).
> Enforcing density floor in EnzoMethodPpm

- tools/l1_error_norm.py
This fixes some failing tests of the VL+CT integrator, that arose because of a recent change in `yt` that affected the python script for computing the L1 Error Norm. I also did some light refactoring.
When accessing field data, the script used a single string to specify the name of the field. Recent versions of `yt` now require that we fully specify the two part names of fields. For more context, I provide a concrete example below:
-  we could previously access density data by specifying  `data['density']`. 
- In reality, `yt` didn't directly track a field called `'density'`. Instead it tracked a field called `'enzoe', 'density'` (this field is specific to enzo-e, corresponds to the data stored on disk, and is in code units) and a field called `'gas', 'density'` (this is a field derived …
> VL+CT test fix

- src/Enzo/enzo_EnzoConfig.hpp
Recent changes to Grackle (changeset 5547acd on Dec. 2) added a couple of attributes to the `chemistry_data` struct that broke Grackle-related circleci tests in Enzo-E. This PR adds the new attributes to the `EnzoConfig::pup()` method (`max_iterations` and `exit_after_iterations_exceeded`), as well as a couple others that I discovered were missing (`dust_recombination_cooling` and `H2_custom_shielding`).
I had previously sorted the attributes in pup(), but have reverted the ordering to that in `grackle_chemistry_data.h` in Grackle to facilitate code reviews.
> Adding missing grackle chemistry pup's

- doc/source/conf.py
In detail, the failing test tries to build the website documentation and fails if any warnings get raised. The test recently started failing (e.g. in PR #280 and PR #263) because the ``sphinx`` developers introduced a new warning to indicate that a configuration option was specified in an outdated format.
In more detail:
* I believe that when ``sphinx`` originally generated our documentation configuration file, ``doc/source/conf.py``, the ``intersphinx`` extension was enabled by default (for the sake of illustrating how to use extensions).
* One of the configuration options that was autogenerated for that extension, called ``intersphinx_mapping``, was specified in a format that was used before version 1.0 of ``sphinx``
* In a recent update to ``sphinx``, the developers introduced a …
> Fixed the failing docs-build circleci test

- src/Cello/parameters_Parameters.cpp
- src/Cello/parameters_Parameters.hpp
Modified the `Parameters::param` to have better behavior when the method is passed an unknown parameter name. For an unknown parameter name `"<param>"`, the method would previously insert the `{"<param>", nullptr}` key-value pair into the `parameter_map_` attribute of `Parameters` before returning a `nullptr`. Now, this method never directly mutates the `parameter_map_` attribute (but it still returns a `nullptr`).
I was motivated to make this change now because the old behavior resulted in unexpected behavior when calling `Parameters::leaf_parameter_names`.
I also checked the other methods of the `Parameters` class and confirmed that none of them actually depended on the old behavior of `Parameters::param`. In fact, many of them included special handling to ignore entries in the …
> Parameters tweaks

- CMakeLists.txt
- cmake/FindGrackle.cmake
This PR modified ``FindGrackle.cmake`` to:
1. prefer linking against static libraries (there was previously a comment in ``FindGrackle.cmake`` expressing the intent to do this, but in practice older versions preferred linking against shared libraries
2. try to query Grackle's version number - this resolves #182
> Modified FindGrackle.cmake to prefer static-library linking and report a Grackle version number

- .circleci/config.yml
- CMakeLists.txt
- doc/source/tutorial/getting_started.rst
- src/Cello/CMakeLists.txt
- src/Enzo/CMakeLists.txt
- src/Enzo/enzo-core/CMakeLists.txt
`BUILD_TESTING` is a commonly occuring option across many different CMake projects. In fact, it is automatically defined by CTest, and was already used to determine whether parts of CTest machinery should be defined. The option is automatica a default value on `ON` (users need to explicitly opt out of building it).
This PR made 3 very small changes:
1. When `BUILD_TESTING` is disabled, we no longer build the unit-test binaries.
2. Documentation about this option has been added.
3. The CircleCI file has been updated to set `BUILD_TESTING=OFF` when building Enzo-E for the purposes of running answer testing
On my personal machine, using the clang compiler and 4 cores, the build step takes 3 minutes 45 seconds when `BUILD_TESTING=ON` and 3 minutes 7 seconds when  `BUILD_TESTING=OFF`.
- This …
> Speed up CI: Modify CMake files to skip unit-test binaries when `BUILD_TESTING` option is `OFF`

- doc/source/tests/pytest_framework.rst
- test/answer_tests/answer_testing.py
- test/answer_tests/conftest.py
- test/answer_tests/test_cosmo.py
- test/answer_tests/test_grackle.py
- test/answer_tests/test_utils/README.md
- test/answer_tests/test_utils/enzoe_driver.py
- test/answer_tests/test_utils/parse_cmake_cache.py
- test/answer_tests/test_vlct.py
This PR introduces a number of small changes that should make the pytest machinery easier to use, particularly when you are switching between multiple branches.
These changes include:
1. Introducing the ability to configure machinery by passing command-line arguments in addition to setting environment variables. Below I list new command-line arguments with their env variable counterparts (when both counterparts are set, the command-line flags have priority):
- `--charm` and `CHARM_PATH`
- `--grackle-input-data-dir` and `GRACKLE_INPUT_DATA_DIR`
- `--local-dir` and `TEST_RESULTS_DIR` (the command line flag borrows the name that `yt` uses)
- `--answer-store` and `GENERATE_TEST_RESULTS` (the command line flag borrows the name that `yt` uses)
2. I introduced the new flag called `--build-dir` …
> Improve ergonomics of pytest machinery

- CMakeLists.txt
- src/Cello/view_ViewCollec.hpp
A number of advantages are highlighted in Issue #317 (C++17 adds a number of useful new features).
The main reasons NOT to do this would be compiler-support. At this point most major compilers support C++17. But since there is ongoing work to introduce dependencies on libraries that require C++17 (like Kokkos or libtorch), this is something of a moot point. Furthermore, there are [discussions of bumping the minimum required compiler version for charm++ to C++17](https://github.com/UIUC-PPL/charm/discussions/3684).
This resolves #317.
This PR includes some minor refactoring of `ViewCollec` to make use of `std::variant`. While similar refactoring is now possible in other areas of the code, I wanted to limit the size of this PR. This fix is somewhat important for robustly addressing some …
> C++ version bump from C++11 to C++17

- .circleci/config.yml
- CMakeLists.txt
- doc/source/tutorial/getting_started.rst
- src/Cello/CMakeLists.txt
- src/Cello/cello.hpp
- src/Enzo/CMakeLists.txt
This introduces the ability to use precompiled headers to speed up the compile times. I had done some light profiling of compile-times with clang's `-ftime-trace` command in order to see where time was being spent during compilation time. 
- As I suspected, we spend a lot of time reading in headers (since every source file reads more headers than necessary). But, the details really surprised me.
- I had been concerned that my `View` template class was increasing compile times by a lot, but it took a negligible amount of time.
- instead a bunch of time is spent reading headers like `<random>`, `<vector>`, `<charm++.h>`, and `<boost/filesystem.h>`. (That last case is addressed separately in PR #320).
To mitigate this to some extent, I started to make use of precompiled headers. This is a …
> Introduce Precompiled Headers to Speed up Compilation 

- .circleci/config.yml
Part 2 of resolving issue #353
This fixes a bug in "extra-compile-tests" job. This job is used to test that Enzo-E can be successfuly be compiled in 2 IMPORTANT compilation configurations that are not tested by any other tests.
The Problem:
- The final step of the "extra-compile-tests" job was failing. This step called the "run-answer-tests" command, which executes the answer-test machinery.
- Specifically, the "run-answer-tests" command failed because the generate parameter was set to false. This means that the command tried to execute the pytest-framework while comparing results to previously generated test-answers. The issue was that there wasn't any previously generated test-answers to be found. (So the command failed - as it should have).
The Solution:
- The solution is simple. We …
> Resolve #353: CircleCI "extra-compile-tests"

- input/PPML/ppml.incl
- src/Cello/parameters_Parameters.hpp
- src/Enzo/enzo-core/EnzoConfig.cpp
The problem in that issue was relatively straight-forward. A while back we introduced a new way to initialize the global EOS object. At that time, I deprecated the `Field:gamma` parameter, but for the sake of backwards compatability I used `Field:gamma` to initialize an ideal EOS.
The error reported in Issue #357 occurred because `Field:gamma` was assigned a value of `1.0` to reflect the fact the PPML solver uses an isothermal function. When the code tried to use this to initialize `EnzoEOSIdeal`, the constructor complained because an adiabatic index of 1 is invalid for the current implementation.
To resolve this situation, I added a more informative error message explaining how the user should fix the problem. I also fixed the PPML test problem's input file to reflect the "correct" way …
> Fix GH Issue #357

- .circleci/config.yml
This PR modifies the CircleCI configuration file to bump the gold-standard version to version 5. 
This will help us fix the broken answer-tests. (The answer-tests will continue to fail in this PR since a `gold-standard-005` tag doesn't exist yet -- our standard procedure is to make the tag after this PR is merged)
Currently answer-tests are broken. This fixes the issue.
The Answer Tests are currently broken for the following reasons:
- ~3 days ago this PR, grackle-project/grackle#184, was merged into Grackle, which removed some deprecated functions from the Grackle codebase.
- Recall that continuous integration always builds the latest commit of Grackle for our tests[^1]
- However, the commit tagged as `gold-standard-004` (from 9 months back) **did** employ these functions. Thus, when our …
> Fix Answer Tests: Update CircleCi to use gold-standard version 5

- src/Enzo/_enzo.hpp
- src/Enzo/assorted/EnzoMethodTurbulence.hpp
This cleans up the `_enzo.hpp` header
I removed the following items (they weren't used anywhere):
- the ``mass_type`` enum
- the ``enzo_fluxes`` struct
- the ``field_undefined`` global constant
I also shifted the `index_turbulence_*` enum family to the header of `EnzoMethodTurbulence.hpp`, which defines the only class that uses these enums).
> Cleanup `_enzo.hpp` header

- src/Enzo/enzo-core/EnzoConfig.cpp
- src/Enzo/enzo-core/EnzoConfig.hpp
- src/Enzo/enzo-core/EnzoProblem.cpp
- src/Enzo/tests/EnzoInitialFeedbackTest.cpp
- src/Enzo/tests/EnzoInitialFeedbackTest.hpp
Followup from #349: moved parameter parsing for `EnzoInitiailFeedbackTest` from `EnzoConfig` into constructor.
**Aside:** This sort of migration is the sort of thing that needs to be done for a lot more examples. This is a great first-time-contribution for new developers. I'm going to create an Issue summarizing the process and that links to this PR as an example (in reality, I will probably link to the particular commit that makes this change).
> Migrate Parameter Parsing: moved configuration of `EnzoInitiailFeedbackTest` into constructor

- src/Enzo/enzo-core/EnzoConfig.cpp
- src/Enzo/enzo-core/EnzoConfig.hpp
- src/Enzo/enzo-core/EnzoProblem.cpp
- src/Enzo/initial/EnzoInitialCloud.hpp
Followup from #349: moved parameter parsing for `EnzoInitiailCloud` from `EnzoConfig` into constructor.
**Aside:** This sort of migration is the sort of thing that needs to be done for a lot more examples. This is a great first-time-contribution for new developers. I'm going to create an Issue summarizing the process and that links to this PR as an example (in reality, I will probably link to the particular commit that makes this change).
> Migrate Parameter Parsing: moved configuration of `EnzoInitiailCloud` into constructor

- src/Cello/cello.cpp
- src/Cello/cello.hpp
- src/Cello/disk_FileHdf5.cpp
- src/Cello/problem_BoundaryValue.cpp
- src/Cello/test_Type.cpp
This is pretty self-explanatory. It turns out that apple-clang on arm-based Macs assign `long double` a size of 8 bytes. Even though it is the same size as a regular `double`, I think it makes more sense to treat it as a discrete type.
> macOS bugfix: support sizeof(long double) == 8

- CMakeLists.txt
- src/Cello/performance_Performance.hpp
- src/Cello/simulation_Simulation.cpp
- src/Enzo/enzo.ci
- src/Enzo/hydro-mhd/EnzoMethodMHDVlct.cpp
This drops a handful of `ifdef` statements involving `CONFIG_USE_GRACKLE`
The benefits are pretty self-explanatory -- namely, it simplifies the codebase. In this particular case, it also simplifies some of the build files. It's also a step towards my goal of removing all of the `CONFIG_USE_GRACKLE` from all headers and just have it in a handful of source files in Enzo's `chemistry` subcomponent (so that rebuilding Enzo-E with/without grackle support can be done as incremental recompilation)
> we dropped a handful of `ifdef` statements involving `CONFIG_USE_GRACKLE`

- src/Cello/_data.hpp
- src/Cello/cello.cpp
- src/Cello/control_adapt.cpp
- src/Cello/data_FieldData.cpp
- src/Cello/data_FieldDescr.cpp
- src/Cello/io_Input.cpp
- src/Cello/io_Output.cpp
- src/Cello/io_OutputData.cpp
- src/Cello/mesh_Adapt.cpp
- src/Cello/mesh_Block.cpp
- src/Cello/mesh_Block.hpp
- src/Cello/mesh_Index.cpp
- src/Cello/monitor_Monitor.cpp
- src/Cello/parameters_Param.cpp
- src/Cello/problem_MethodOrderMorton.cpp
- src/Cello/simulation_Simulation.cpp
- src/Cello/simulation_Simulation.hpp
- src/Cello/test_Error.cpp
- src/Cello/test_Performance.cpp
- src/Enzo/fluid-props/EnzoEOSIdeal.hpp
- src/Enzo/gravity/solvers/EnzoSolverBiCgStab.cpp
As mentioned in #390, macOS has decided that `sprintf` is deprecated, which produces a lot of annoying compiler warnings. This replaces all occurrences of `sprintf` outside of the parsing code (which is addressed by #390)
This is pretty self-explanatory. I would have loved to have consolidated the implementations of `cello::expand_name` and `Output::expand_name_``, but I was a little confused about the differences (and I was trying to get through this relatively quickly).
Aside: In case you're unaware, if you declare a c-style array
```c
char my_arr[14];
```
then calling `sizeof(my_arr)` gives the total size of the array in bytes (in contrast, calling `sizeof` on a pointer just gives the size of the pointer). I take advantage of this a lot throughout this PR.
This PR has no dependencies. …
> Replacing sprintf

- doc/source/devel/cmake_primer.rst
- doc/source/devel/coding-guidelines.rst
- src/Enzo/CMakeLists.txt
- src/Enzo/enzo-core/CMakeLists.txt
This modifies `src/Enzo/CMakeLists.txt` and `src/Enzo/enzo-core/CMakeLists.txt` so that the source files are no longer fetched with globbing expressions.
After this PR is merged and #386 is merged, there will no longer be any globbing expressions in the Enzo layer. Other PRs that made similar changes include https://github.com/enzo-project/enzo-e/pull/332 - https://github.com/enzo-project/enzo-e/pull/336 as well as #367. 
The other aforementioned PRs also converted the other subdirectories into separate "subcomponents." Essentially the source files were grouped together into distinct CMake targets (they're usually compiled into a distinct static-library) and their headers were removed from `src/Enzo/_enzo.hpp`, and inserted into a single separate header (for this scenario the analogous …
> Remove last Enzo layer cmake-`GLOB`s

- doc/source/param/method_mhd_vlct.incl
- src/Enzo/hydro-mhd/EnzoMethodMHDVlct.cpp
This is pretty self-explanatory. I removed 2 deprecated parameters from the VL+CT solver.
The VL+CT solver still has a few other remaining deprecated parameters but those are a little tricky to remove (since they are now employed by to configure `EnzoPhysicsFluidProps`). The PPM solver has a similar set of deprecated parameters and I think they should both be removed at the same time
> remove deprecated `Method:mhd_vlct:{half,full}_dt_reconstruct_method` parameters

- input/vlct/run_MHD_linear_wave_test.py
- input/vlct/testing_utils.py
I adjusted the tolerance on MHD slow magnetosonic wave so that the test passes on macOS.
In more detail,
- I confirmed that on my older linux machine, the L1 error norms are extremely consistent with the existing value (regardless of whether I use gcc or clang). In other words, I confirmed that nothing has broken the tests. (we pretty much knew that already based on circleci, but it was nice confirmation)
- It turns out that the results are just shockingly different on my MacBook (regardless of whether I use g++ or apple-clang).
My assumption is that some combination of the differences in operating systems and the differences in architectures cause differences in how floating-point values get rounded and those differences compound over the course of the test.
ASIDE: I have confirmed that …
> Adjusting the tolerance for MHD slow magnetosonic wave

- input/LoadBalance/test_hilbert-balance-on-bcg.in
- src/Cello/_problem.hpp
- src/Cello/mesh.ci
- src/Cello/mesh_Block.hpp
- src/Cello/problem_MethodOrderHilbert.cpp
- src/Cello/problem_MethodOrderHilbert.hpp
- src/Cello/problem_Problem.cpp
- src/Enzo/enzo-core/EnzoMethodBalance.cpp
- test/CMakeLists.txt
A `MethodOrderHilbert` class was added which uses a Hilbert curve to order blocks in a simulation.
The class is largely based on the MethodOrderMorton class but with some key logic/functions replaced with Hilbert versions. Namely, the logic for iterating over child blocks in a Morton order was replaced with a Hilbert version (facilitated by a `hilbert_children` function) and the `Index.next` method was replaced with `MethodOrderHilbert::hilbert_next`.
The algorithms for determining the Hilbert order are based on those presented in "Mengjuan Li et al 2023 (Efficient entry point encoding and decoding algorithms on 2D Hilbert space filling curve)" and "Lianyin Jia et al 2022 (Efficient 3D Hilbert curve encoding and decoding algorithms)" which are iterative and use look-up tables rather than …
> Hilbert order method for load balancing 

- src/Enzo/io/EnzoInitialHdf5.cpp
Fixed a spot in `EnzoInitialHdf5` where we were using variable length arrays.
In more detail, VLAs (variable length arrays) are a feature of C99 and are not supported in C++. g++ happens to support the feature, but other compilers (like clang++) don't. Thus builds on macOS were broken.
This fixes #407.
> Remove usage of VLA -- it breaks default macOS builds (and use of clang in general)

- tools/l1_error_norm.py
Our CI tests have now started using a numpy 2.0 (since we don't pin python versions). That release removed `numpy.recfromtxt`, which caused some of our tests to fail.
This PR simply replaces `np.recfromtxt` with `np.genfromtxt`.
> Fix-failing-CI tests: No longer using removed numpy function

- src/Cello/data_Object.hpp
Fixing a minor bug in the ``Object`` class's copy-assignment operation. Currently it doesn't return a reference. I switched the implementation so that it now uses the default implementation.
While I was here, I modified the constructor and the copy-constructor to use the default implementation since there is no semantic difference (and it can sometimes produce faster code) 
> minor bugfix - Object's copy-assignment operation is currently wrong -- It doesn't return anything.

- src/Enzo/enzo-core/EnzoUnits.hpp
- src/Enzo/gravity/EnzoPhysicsGravity.hpp
- src/Enzo/particle/formation/EnzoMethodStarMakerSTARSS.hpp
There are a few spots in the codebase where we have started to make use of the ``override`` keyword (it tells the compiler to make sure that you are actually overriding an existing virtual function - this is an extremely useful feature).
The clang compiler provides warnings if some virtual methods within a given class are annotated with ``override`` while other methods are not annotated. (It dislikes the inconsistency -- and I think it's a fair complaint)
This change addresses that warning by using ``override`` more consistently throughout the class (where we had already used it once it in the past)
> Suppress inconsistent ``override`` warnings.

- CMakeLists.txt
This commit introduces a minor tweak to the way in which charm++'s linker-flags (related to balancers and modules) are specified in order to let us use newer versions of charm++.
This fixes GitHub Issue #201.
I only tested that Enzo-E could compile with charm++ version 8.0 (I didn't actually run any tests -- that will take a little more effort)
> CMake tweak to support newer charm++ versions -- fix gh-#201

- .readthedocs.yaml
ReadTheDocs has broken CI builds builds unless you explicitly specify that we are building sphinx docs
> Fix ReadTheDocs doc CI build
